[plugins]
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.2.3" }
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

[versions]
kyori = "4.16.0"
bundle = "1.20.4-R0.1-SNAPSHOT"
cluster = "1.0-SNAPSHOT"

[libraries]
simple-yaml = { group = "com.github.Carleslc.Simple-YAML", name = "Simple-Yaml", version = "1.8.4" }

minimessage-api = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "kyori" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "kyori" }

itemsadder-api = { group = "com.github.LoneDev6", name = "api-itemsadder", version = "3.6.1" }
oraxen-api = { group = "io.th0rgal", name = "oraxen", version = "1.171.0" }
placeholder-api = { group = "me.clip", name = "placeholderapi", version = "2.11.5" }
head-database-api = { group = "com.arcaniax", name = "HeadDatabase-API", version = "1.3.1" }

paperweight-userdev = { group = "io.papermc.paperweight.userdev", name = "io.papermc.paperweight.userdev.gradle.plugin", version = "1.5.11" }
publishing-modrinth = { group = "com.modrinth.minotaur", name = "Minotaur", version = "2.8.7" }
publishing-hangar = { group = "io.papermc", name = "hangar-publish-plugin", version = "0.1.2" }

cluster-api = { group = "com.ryderbelserion.cluster", name = "api", version.ref = "cluster" }
cluster-paper = { group = "com.ryderbelserion.cluster", name = "paper", version.ref = "cluster" }

fancy-holograms = { group = "de.oliver", name = "FancyHolograms", version = "2.0.6" }
decent-holograms = { group = "com.github.decentsoftware-eu", name = "decentholograms", version = "2.8.6" }

worldedit = { group = "com.sk89q.worldedit", name = "worldedit-bukkit", version = "7.2.15" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version = "7.1.0-SNAPSHOT" }

nbtapi = { group = "de.tr7zw", name = "item-nbt-api", version = "2.12.2" }

triumph-cmds = { group = "dev.triumphteam", name = "triumph-cmd-bukkit", version = "2.0.0-ALPHA-9" }
triumph-gui = { group = "dev.triumphteam", name = "triumph-gui", version = "3.1.7" }

vault = { group = "com.github.MilkBowl", name = "VaultAPI", version = "1.7.1" }
metrics = { group = "org.bstats", name = "bstats-bukkit", version = "3.0.2" }
config-me = { group = "ch.jalu", name = "configme", version = "1.4.1" }

griefprevention = { group = "com.github.TechFortress", name = "GriefPrevention", version = "16.18.2" }
towny = { group = "com.palmergames.bukkit.towny", name = "towny", version = "0.100.2.0" }
factions = { group = "com.massivecraft", name = "Factions", version = "1.6.9.5-U0.6.31" }

skyblock = { group = "com.bgsoftware", name = "SuperiorSkyblockAPI", version = "2023.2" }
plotsquared = { group = "com.plotsquared", name = "PlotSquared-Core", version = "6.11.1" }
mcmmo = { group = "com.gmail.nossr50.mcMMO", name = "mcMMO", version = "2.2.0-SNAPSHOT" } # https://repo.codemc.io/service/rest/repository/browse/maven-public/com/gmail/nossr50/mcMMO/mcMMO/
wildstacker = { group = "com.bgsoftware", name = "WildStackerAPI", version = "2023.2" }

kingdoms = { group = "com.github.cryptomorin", name = "kingdoms", version = "1.16.20.5"}

informative-annotations = { group = "com.intellectualsites.informative-annotations", name = "informative-annotations", version = "1.3" }
paster = { group = "com.intellectualsites.paster", name = "Paster", version = "1.1.5" }

nocheatplus = { group = "fr.neatmonster", name = "nocheatplus", version = "3.16.1-SNAPSHOT" }

[bundles]
adventure = ["minimessage-api", "adventure-api"]
holograms = ["fancy-holograms", "decent-holograms"]
triumph = ["triumph-cmds", "triumph-gui"]