[versions]

# Project Settings
github = "https://github.com/Crazy-Crew/CrazyEnchantments"
beta = "true"
extension = "plugin"

[plugins]

minotaur = { id = "com.modrinth.minotaur", version = "2.7.5" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "2.0.1" }